### PR TITLE
De-ASM-ification - RenderManager#doRenderEntity

### PR DESCRIPTION
**Pull request by Elix-x**
De-ASM-ified RenderManager#doRenderEntity using reflection load time replacement with override class intercepting methods we were patching with ASM.
Comes with minor performance improvements (indirectly reduces number of GL calls).
Piggies!

### CODE REVIEW

**Comment by BigBastard** [comment]
1 less ASM call to worry about great work :D

I am however concerned about the issues this could bring for either shaders or Optifine, which may be replacing the RenderManager object themselves. I'll test it out and post back on here.

**Comment by BigBastard** [comment]
There's been talk on the discord that update #76 on Jenkins turned all the entities from Mo Creatures mod invisible.

:/

**Comment by DaMatrix** [comment]
AUGHHHH MORE GL STUFF SAVE ME PLS

**Comment by Elix-x** [comment]
Quickly looking through decompiled source, i have not found anything related to this PR.
This issue definitely requires more elaborate investigation.

**Pull request merged**
