### PR TITLE
new new chair nuke

### PR DESCRIPTION
**Pull request by DeltaNedas**
please

### CODE REVIEW

**Comment by zayats1** [comment]
This  should   be  a  config option
#Enable pilot chair
#default true/false
false
(for  me and noobs recomend  true)
)
:netbeans:

**Comment by DaMatrix** [comment]
the pilot's chair is going to be reworked at some point soon, this is more of a temporary removal to avoid people asking questions about the broken mechanics until it's reworked

**Comment by DeltaNedas** [comment]
no
git gud

**Comment by Rubydesic** [comment]
Sorry, but we're not planning on doing this at this time. Thanks for your PR.

**Pull request closed without merging**
