### PR TITLE
1.11.2 update!!!

### PR DESCRIPTION
**Pull request by DaMatrix**
Don't merge yet lol

### CODE REVIEW

**Comment by DaMatrix** [comment]
I think this is more or less ready to be merged, but I'm going to wait until #99 is done before merging it as mixins are much easier to keep on top of

**Comment by DaMatrix** [comment]
we're 1.11.2 now!!!!!

**Comment by JackTheRedCreeper** [comment]
1.10.2 forevah!

**Comment by DaMatrix** [comment]
no, 1.7.2 beta forever!
@BigBastard when are we downgrading

**Pull request merged**
