### PR TITLE
Prevent infusing water and lava, and add a simple way of blocking other blocks should ne need arise.

### PR DESCRIPTION
**Pull request by DaMatrix**
Fixes part of #67

### CODE REVIEW

**Comment by Liiw** [comment]
Hi!

Just tried build 101 and it's displaying the "too big or attached to bedrock" message on every vessel I try infusing on. This happens whether or not the vessel is in water or in mid-air.

**Comment by BigBastard** [comment]
That functionality already exists in ValkyrienWarfareBase/Relocation/ShipSpawnDetector.java

The other detector class is used by the clients to generate a list of every BlockPos that isn't air. I'm not sure what kind of effects removing water from ships would have.

**Comment by DaMatrix** [comment]
@Liiw yeah, I forgot to add air to the blacklist :P 
@BigBastard from what I saw the only block that was being blocked was air

**Comment by BigBastard** [comment]
Alright fair enough, I see what you mean that certain blocks like water and lava should not be considered in calculations involving mass.

I'll modify the PhysicsObject.onSetBlockState() method to use this blacklist, and then merge the pull.

**Pull request merged**
