### PR TITLE
Fixed null pointers by pointing directly to now static variables

### PR DESCRIPTION
**Pull request by LightningSh0ck**
This is fixing null pointer crashes as well as missing textures that occur on the built version(dev was not affected somehow).

### CODE REVIEW

**Comment by Best108** [comment]
Looks promising, though I'll have to consult with @DaMatrix first before merging

**Comment by DaMatrix** [comment]
Making everything static should **_NEVER_** be the solution.  The problem should be fixed at the base (why is `INSTANCE` still null, even though it's set in the constructor?)

**Comment by LightningSh0ck** [comment]
The thing is that INSTANCE itself is not NULL(I tested it myself beforehand), it's methods are being accessed just fine, however it's variables don't. Seeing no usefulness in keeping them non-static as they are going to be unique and used once anyway, I made them static.

**Comment by DaMatrix** [comment]
I think there's a bigger root cause of this (specifically that we're somehow creating multiple instances of modules).  That should have been fixed by https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/commit/e36b2aacf329cc9a73b6d7cbfd673f5136a477ae#diff-115785684b66732f42fe33430d765da1

**Comment by LightningSh0ck** [comment]
I've noticed I missed out some spots. Even if it runs, there are still leftover spots in the code I did not replace which might behave unexpectedly. I will fix that first.

**Comment by LightningSh0ck** [comment]
Nevermind, I think I realized why do you feel like this is a "duct tape" fix. But I also realized something

@DaMatrix in your latest commit look in src\main\java\valkyrienwarfare\ValkyrienWarfareMod.java again at lines 235 and 304, that is creating multiple instances. I suggest getting rid of code in 235.

**Pull request closed without merging**
